'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const test=require('node:test');
const policy=require('../core/vobix-child-protection');const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8');
test('Capa 106 está registrada sin afirmar vigilancia de conversaciones',()=>{const layers=read('core/vobix-layers.js');assert.match(layers,/id:'106'.*Vobix Protección Infantil.*status:'en_validacion'/);assert.match(read('server.js'),/no concede acceso al contenido del chat/);});
test('los horarios normales y nocturnos se calculan en minutos UTC',()=>{assert.deepEqual(policy.validSchedule(480,1200),{start:480,end:1200});assert.equal(policy.validSchedule(1,1),null);assert.equal(policy.isAllowedNow({start:1320,end:420},new Date('2026-01-01T23:00:00Z')),true);assert.equal(policy.isAllowedNow({start:1320,end:420},new Date('2026-01-01T12:00:00Z')),false);});
test('emergencias nunca quedan bloqueadas por horario o contacto',()=>{assert.deepEqual(policy.policyDecision({active:true,blockUnknown:true,knownContact:false,emergency:true}),{allowed:true,reason:'emergency'});assert.equal(policy.policyDecision({active:true,blockUnknown:true,knownContact:false}).reason,'unknown_contact');});
test('la activación exige consentimiento del menor y del tutor verificado',()=>{const server=read('server.js');assert.match(server,/req\.body\?\.childConsent !== true/);assert.match(server,/status='active' LIMIT 1/);assert.match(server,/req\.body\?\.guardianConsent!==true/);assert.match(server,/status='pending_guardian'/);});
test('cualquiera de las dos partes puede desactivar la vinculación',()=>{const server=read('server.js');assert.match(server,/child_user_id=\$1 OR guardian_user_id=\$1/);assert.match(server,/SET status='disabled',disabled_at=NOW\(\)/);});
test('el esquema limita estados, horario y contactos autorizados',()=>{const schema=read('database/schema.js');assert.match(schema,/CREATE TABLE IF NOT EXISTS child_protection_profiles/);assert.match(schema,/CHECK\(status IN \('pending_guardian','active','declined','disabled'\)\)/);assert.match(schema,/CREATE TABLE IF NOT EXISTS child_allowed_contacts/);});
